version: '3.4'

services:

  controlroom-api:
    image: ${REGISTRY:-rover}/controlroom.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: applications/controlroom.api/controlroom.api/Dockerfile
    depends_on:
      - seq
      - sqldata
      - rabbitmq

  rover:
    image: ${REGISTRY:-rover}/rover:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: applications/rover/rover/Dockerfile
    depends_on:
      - seq
      - sqldata
      - rabbitmq
  
  controlroom-ui:
    image: ${REGISTRY:-rover}/controlroom.ui:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: applications/controlroom-ui/Dockerfile
    depends_on:
      - controlroom-api