version: '3.4'

services:

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - marsrover-sqldata:/var/opt/mssql

  nosqldata:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - marsrover-nosqldata:/data/db

  # redisdata:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - marsrover-redisdata:/data
  
  # eventstore:
  #   image: eventstore/eventstore:release-5.0.1
  #   container_name: eventstore
  #   ports:
  #     - 2113:2113
  #     - 1113:1113
  #   restart: always
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
  #     interval: 5s
  #     timeout: 2s
  #   environment:
  #     - EVENTSTORE_RUN_PROJECTIONS=all
  #     - EVENTSTORE_START_STANDARD_PROJECTIONS=TRUE

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  marsrover-sqldata:
    external: false
  marsrover-nosqldata:
    external: false
  # marsrover-redisdata:
  #   external: false

  