version: '3.4'

services:

  # seq:
  #   image: datalust/seq:latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "5340:80"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - marsrover-sqldata:/var/opt/mssql

  nosqldata:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - marsrover-nosqldata:/data/db

  redisdata:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - marsrover-redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=admin
    command: "/bin/bash -c \"rabbitmq-plugins enable rabbitmq_mqtt; rabbitmq-server\""
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
    volumes:
      - "./rabbitmq:/etc/rabbitmq"

volumes:
  marsrover-sqldata:
    external: false
  marsrover-nosqldata:
    external: false
  marsrover-redisdata:
    external: false

  