name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: src
      run: docker build . --file applications/controlroom.api/controlroom.api/Dockerfile --tag controlromm-api-marsrover:$(date +%s)
