name: Docker Image Rover CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}/rover:$(date +%s)
  
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: src
        run: docker build . --file applications/rover/rover/Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - uses: actions/checkout@v2
      - name: Push the Docker image
        working-directory: src
        run: docker push  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


