name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./src/rover.sln
      
    - name: Test
      run: dotnet test ./src/modules/rover/rover.unittests/rover.unittests.csproj -c Release --logger "trx;LogFileName=test_results_unit_test.trx" -p:CollectCoverage=true -p:CoverletOutput="testResults/coverage.info" -p:CoverletOutputFormat=lcov
    
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
      uses: codecov/codecov-action@v2.1.0
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: d84c93c6-9bff-41e4-bb48-95974fb8b836
        # Comma-separated list of files to upload
        #files: # optional
        # Directory to search for coverage reports.
        directory: ./src/modules/rover/rover.unittests/testResults
        verbose: true
